# Generated by Django 5.0.1 on 2024-01-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_of_active_task',
            field=models.IntegerField(default=0),
        ),
    ]
