# Generated by Django 4.2.7 on 2023-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcategory_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
