version: '3.8'

services:
  django-app:
    build: ../backend/
    networks:
      - todo

  angular-app:
    build: ../frontend/todo
    depends_on:
      - django-app
    networks:
      - todo
      
networks:
  todo: