version: '3.8'

services:

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    networks:
      - todo

  db:
    image: mysql:8.3.0
    container_name: todoDBContainer
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - todo

  backend:
    build: ../backend/
    container_name: todoApiContainer
    command: sh -c "python3 manage.py collectstatic && gunicorn --worker-class gevent -w 4 todo.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    networks:
      - todo

  asgiserver:
    build: ../backend/
    container_name: todoAsgiContainer
    command: daphne todo.asgi:application -b 0.0.0.0 -p 9000
    depends_on:
      - db
      - redis
    ports:
      - 9000:9000
    networks:
      - todo

  frontend:
    build: ../frontend/todo
    container_name: todoClientContainer
    depends_on:
      - backend
    networks:
      - todo

volumes:
  data:
      
networks:
  todo: