# Generated by Django 5.0.1 on 2024-02-08 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
        ('task', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='task_task_categor_21337f_idx'),
        ),
    ]
