# Generated by Django 5.0.1 on 2024-01-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='position',
        ),
    ]
