# Generated by Django 5.0.1 on 2024-01-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('category', '0005_alter_category_title'),
        ('task', '0002_task_category_task_user'),
        ('users', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
