# Generated by Django 5.0.1 on 2024-01-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
